version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3000
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/supplement_reminder
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=supplement_reminder
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

# This Docker Compose file is for local development and testing.
# For production, use container orchestration platforms like Amazon ECS or Kubernetes.