apiVersion: v1
kind: ConfigMap
metadata:
  name: supplement-reminder-config
  namespace: supplement-reminder
  labels:
    app: supplement-reminder
    environment: production
  annotations:
    kubernetes.io/change-cause: "Initial ConfigMap configuration for supplement reminder application"
    last-updated: "2023-06-15"
data:
  # Application environment
  NODE_ENV: "production"
  
  # API configuration
  API_URL: "https://api.supplement-reminder.example.com"
  API_VERSION: "v1"
  
  # Reminder settings
  REMINDER_MESSAGE: "Bon voyage! Take the supplement so you feel better tomorrow!"
  MAX_REMINDERS_PER_USER: "5"
  REMINDER_TIMEZONE: "UTC"
  
  # Feature flags
  ANALYTICS_ENABLED: "true"
  
  # Logging configuration
  LOG_LEVEL: "info"
  
  # Performance tuning
  MAX_CONCURRENT_CONNECTIONS: "100"
  
  # Security settings
  CORS_ALLOWED_ORIGINS: "https://supplement-reminder.example.com"
  
  # Monitoring and health check
  HEALTH_CHECK_ENDPOINT: "/health"
  
  # Caching configuration
  CACHE_TTL: "3600"
  
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: "900000"  # 15 minutes
  RATE_LIMIT_MAX_REQUESTS: "100"